name = "VS Code"
description = "Visual Studio Code theme extension"
version = "1.0"
condition = "code"

[[files]]
template = "package.json"
destination = "~/.vscode/extensions/peachy-theme/package.json"

[[files]]
template = "peachy-color-theme.json"
destination = "~/.vscode/extensions/peachy-theme/themes/peachy-color-theme.json"
