run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: peachy

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
