# Peachy colors for Dunst
# Include in dunstrc: include = ~/.config/dunst/peachy-colors.conf

[global]
    frame_color = "{magenta}"
    separator_color = frame

[urgency_low]
    background = "{background}"
    foreground = "{foreground}"
    frame_color = "{bright_black}"

[urgency_normal]
    background = "{background}"
    foreground = "{foreground}"
    frame_color = "{magenta}"

[urgency_critical]
    background = "{red}"
    foreground = "{background}"
    frame_color = "{bright_red}"
